### ISSUE TITLE
question about data source

### ISSUE THREAD

**Issue by rumtsv** [sjufan84/esg_risk_parity#1]
Hello.  I am currently writing a paper at the university on ESG. Could you please tell me where you got the data on esg scores for "Machine Learning and Heirarchical Risk Parity ESG Portfolio Construction".  Thanks in advance for your reply.

**Comment by sjufan84** [comment]
Hi, apologies for the late response!  I used a rapidapi located here -- https://rapidapi.com/esg.enterprise.app/api/esg-environmental-social-governance-data/.   I haven't tried it in a while, but I assume it still works.  Let me know if you have any other questions.  Hope that helps!

Dave
